/* Generated By:JavaCC: Do not edit this line. Lovelace.java */
import java.io.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import ast.*;

public class Lovelace implements LovelaceConstants {
    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Uso: java Lovelace <arquivo.lov>");
            return;
        }

        try {
            Lovelace lexer = new Lovelace(new FileInputStream(args[0]));
            lexer.Analise();
            System.out.println("\nAnalise lexica concluida com sucesso!");

            Lovelace parser = new Lovelace(new FileInputStream(args[0]));
            Prog arvore = parser.Lovelace();
            System.out.println("\nAnalise sintatica concluida com sucesso!");
            geraCodigo(arvore, args[0]);
        } catch (FileNotFoundException e) {
            System.err.println("Erro: Arquivo nao encontrado - " + args[0]);
        } catch (Exception e) {
            System.err.println("Erro durante analise: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public static void geraCodigo(Prog prog, String arquivo) {
        try {
            String codigo = gerarPrograma(prog);
            Path outPath = Paths.get(gerarNomeSaida(arquivo));
            Files.write(outPath, codigo.getBytes(StandardCharsets.UTF_8));
            System.out.println("Codigo C gerado em: " + outPath.toAbsolutePath());
        } catch (IOException e) {
            System.err.println("Erro ao gerar codigo: " + e.getMessage());
        }
    }

    private static String gerarPrograma(Prog prog) {
        StringBuilder sb = new StringBuilder();
        sb.append("#include <stdio.h>\n");
        sb.append("#include <stdlib.h>\n");
        sb.append("#include <stdbool.h>\n\n");

        Map<String, String> funReturn = new HashMap<String, String>();
        if (prog.fun != null) {
            for (Fun fun : prog.fun) {
                funReturn.put(fun.nome, fun.retorno);
            }
        }

        if (prog.fun != null) {
            for (Fun fun : prog.fun) {
                emitirFuncao(sb, fun, funReturn);
                sb.append("\n");
            }
        }

        emitirMain(sb, prog.main, funReturn);
        return sb.toString();
    }

    private static void emitirFuncao(StringBuilder sb, Fun fun, Map<String, String> funReturn) {
        sb.append(tipoC(fun.retorno)).append(" ").append(fun.nome).append("(");

        if (fun.params != null) {
            for (int i = 0; i < fun.params.size(); i++) {
                ParamFormalFun p = fun.params.get(i);
                if (i > 0) sb.append(", ");
                sb.append(tipoC(p.type)).append(" ").append(p.var);
            }
        }
        sb.append(") {\n");

        Map<String, String> env = new HashMap<String, String>();
        if (fun.params != null) {
            for (ParamFormalFun p : fun.params) {
                env.put(p.var, p.type);
            }
        }
        if (fun.vars != null) {
            for (VarDecl v : fun.vars) {
                env.put(v.var, v.type);
                sb.append(indent(1)).append(tipoC(v.type)).append(" ").append(v.var).append(";\n");
            }
        }

        emitirComandos(sb, fun.body, 1, env, funReturn);
        sb.append("}\n");
    }

    private static void emitirMain(StringBuilder sb, Main main, Map<String, String> funReturn) {
        sb.append("int main(void) {\n");
        Map<String, String> env = new HashMap<String, String>();
        if (main.vars != null) {
            for (VarDecl v : main.vars) {
                env.put(v.var, v.type);
                sb.append(indent(1)).append(tipoC(v.type)).append(" ").append(v.var).append(";\n");
            }
        }
        emitirComandos(sb, main.coms, 1, env, funReturn);
        sb.append(indent(1)).append("return 0;\n");
        sb.append("}\n");
    }

    private static void emitirComandos(StringBuilder sb, ArrayList<Comando> coms, int nivel,
                                       Map<String, String> env, Map<String, String> funReturn) {
        if (coms == null) return;
        for (Comando c : coms) {
            emitirComando(sb, c, nivel, env, funReturn);
        }
    }

    private static void emitirComando(StringBuilder sb, Comando c, int nivel,
                                      Map<String, String> env, Map<String, String> funReturn) {
        if (c instanceof CAtribuicao) {
            CAtribuicao cmd = (CAtribuicao) c;
            sb.append(indent(nivel)).append(cmd.var).append(" = ")
                .append(emitirExp(cmd.exp, env, funReturn)).append(";\n");
            return;
        }
        if (c instanceof CReadInput) {
            CReadInput cmd = (CReadInput) c;
            String tipo = env.getOrDefault(cmd.var, "Float");
            String fmt = tipo.equals("Bool") ? "%d" : "%f";
            sb.append(indent(nivel)).append("scanf(\"").append(fmt).append("\", &")
                .append(cmd.var).append(");\n");
            return;
        }
        if (c instanceof CPrint) {
            CPrint cmd = (CPrint) c;
            String tipo = inferirTipo(cmd.exp, env, funReturn);
            String fmt = tipo.equals("Bool") ? "%d\\n" : "%f\\n";
            sb.append(indent(nivel)).append("printf(\"").append(fmt).append("\", ")
                .append(emitirExp(cmd.exp, env, funReturn)).append(");\n");
            return;
        }
        if (c instanceof CIf) {
            CIf cmd = (CIf) c;
            sb.append(indent(nivel)).append("if (")
                .append(emitirExp(cmd.exp, env, funReturn)).append(") {\n");
            emitirComandos(sb, cmd.bloco, nivel + 1, env, funReturn);
            sb.append(indent(nivel)).append("}\n");
            return;
        }
        if (c instanceof CWhile) {
            CWhile cmd = (CWhile) c;
            sb.append(indent(nivel)).append("while (")
                .append(emitirExp(cmd.exp, env, funReturn)).append(") {\n");
            emitirComandos(sb, cmd.bloco, nivel + 1, env, funReturn);
            sb.append(indent(nivel)).append("}\n");
            return;
        }
        if (c instanceof CReturn) {
            CReturn cmd = (CReturn) c;
            sb.append(indent(nivel)).append("return ")
                .append(emitirExp(cmd.exp, env, funReturn)).append(";\n");
            return;
        }
        if (c instanceof CChamadaFun) {
            CChamadaFun cmd = (CChamadaFun) c;
            sb.append(indent(nivel)).append(cmd.fun).append("(");
            if (cmd.args != null) {
                for (int i = 0; i < cmd.args.size(); i++) {
                    if (i > 0) sb.append(", ");
                    sb.append(emitirExp(cmd.args.get(i), env, funReturn));
                }
            }
            sb.append(");\n");
        }
    }

    private static String emitirExp(ast.Exp exp, Map<String, String> env, Map<String, String> funReturn) {
        if (exp instanceof EFloat) {
            return Float.toString(((EFloat) exp).value);
        }
        if (exp instanceof EVar) {
            return ((EVar) exp).var;
        }
        if (exp instanceof ETrue) {
            return "1";
        }
        if (exp instanceof EFalse) {
            return "0";
        }
        if (exp instanceof EChamadaFun) {
            EChamadaFun call = (EChamadaFun) exp;
            StringBuilder sb = new StringBuilder();
            sb.append(call.fun).append("(");
            if (call.args != null) {
                for (int i = 0; i < call.args.size(); i++) {
                    if (i > 0) sb.append(", ");
                    sb.append(emitirExp(call.args.get(i), env, funReturn));
                }
            }
            sb.append(")");
            return sb.toString();
        }
        if (exp instanceof EOpExp) {
            EOpExp op = (EOpExp) exp;
            return "(" + emitirExp(op.arg1, env, funReturn) + " " + op.op + " "
                + emitirExp(op.arg2, env, funReturn) + ")";
        }
        return "0";
    }

    private static String inferirTipo(ast.Exp exp, Map<String, String> env, Map<String, String> funReturn) {
        if (exp instanceof ETrue || exp instanceof EFalse) return "Bool";
        if (exp instanceof EFloat) return "Float";
        if (exp instanceof EVar) return env.getOrDefault(((EVar) exp).var, "Float");
        if (exp instanceof EChamadaFun) {
            return funReturn.getOrDefault(((EChamadaFun) exp).fun, "Float");
        }
        if (exp instanceof EOpExp) {
            String op = ((EOpExp) exp).op;
            if (op.equals("&&") || op.equals("||") || op.equals("==") ||
                op.equals("<") || op.equals(">") || op.equals("<=") || op.equals(">=")) {
                return "Bool";
            }
            return "Float";
        }
        return "Float";
    }

    private static String tipoC(String tipo) {
        if ("Bool".equals(tipo)) return "int";
        if ("Void".equals(tipo)) return "void";
        return "float";
    }

    private static String indent(int nivel) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < nivel; i++) sb.append("    ");
        return sb.toString();
    }

    private static String gerarNomeSaida(String arquivo) {
        int idx = arquivo.lastIndexOf('.');
        if (idx > 0) return arquivo.substring(0, idx) + ".c";
        return arquivo + ".c";
    }

/* ANALISE LEXICA */
  final public void Analise() throws ParseException {
    Token t;
        try {
            while (true) {
                t = getNextToken();
                if (t.kind == EOF) break;
                switch (t.kind) {
                    case MAIN: System.out.println("Palavra reservada: main"); break;
                    case BEGIN: System.out.println("Palavra reservada: begin"); break;
                    case END: System.out.println("Palavra reservada: end"); break;
                    case LET: System.out.println("Palavra reservada: let"); break;
                    case IF: System.out.println("Palavra reservada: if"); break;
                    case ELSE: System.out.println("Palavra reservada: else"); break;
                    case WHILE: System.out.println("Palavra reservada: while"); break;
                    case READ: System.out.println("Palavra reservada: read"); break;
                    case RETURN: System.out.println("Palavra reservada: return"); break;
                    case PRINT: System.out.println("Palavra reservada: print"); break;
                    case DEF: System.out.println("Palavra reservada: def"); break;
                    case FLOAT: System.out.println("Tipo: Float"); break;
                    case BOOLEAN: System.out.println("Tipo: Bool"); break;
                    case VOID: System.out.println("Tipo: Void"); break;
                    case TRUE: System.out.println("Valor booleano: true"); break;
                    case FALSE: System.out.println("Valor booleano: false"); break;
                    case MAIS: System.out.println("Operador aritmetico: +"); break;
                    case MENOS: System.out.println("Operador aritmetico: -"); break;
                    case MULT: System.out.println("Operador aritmetico: *"); break;
                    case DIV: System.out.println("Operador aritmetico: /"); break;
                    case AND: System.out.println("Operador logico: &&"); break;
                    case OR: System.out.println("Operador logico: ||"); break;
                    case IGUAL: System.out.println("Operador relacional: =="); break;
                    case MENOR: System.out.println("Operador relacional: <"); break;
                    case MAIOR: System.out.println("Operador relacional: >"); break;
                    case MENOR_IGUAL: System.out.println("Operador relacional: <="); break;
                    case MAIOR_IGUAL: System.out.println("Operador relacional: >="); break;
                    case ATRIBUICAO: System.out.println("Operador de atribuicao: :="); break;
                    case ABRE_PAR: System.out.println("Abre parenteses: ("); break;
                    case FECHA_PAR: System.out.println("Fecha parenteses: )"); break;
                    case VIRGULA: System.out.println("Virgula: ,"); break;
                    case PONTO_VIRGULA: System.out.println("Ponto e virgula: ;"); break;
                    case IDENTIFICADOR: System.out.println("Identificador: " + t.image); break;
                    case NUM: System.out.println("Numero: " + t.image); break;
                    case STRING: System.out.println("String: " + t.image); break;
                    default: System.out.println("Token desconhecido: " + t.image); break;
                }
            }
        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
        }
  }

/* ANALISE SINTATICA */
  final public Prog Lovelace() throws ParseException {
 Main main=null; ArrayList<Fun> funs = new ArrayList<Fun>(); Fun f=null;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DEF:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      f = Func();
               funs.add(f);
    }
    main = LovMain();
    jj_consume_token(0);
     {if (true) return new Prog(main,funs);}
    throw new Error("Missing return statement in function");
  }

  final public Main LovMain() throws ParseException {
 ArrayList<VarDecl> vars=null; ArrayList<Comando> coms=null;
    jj_consume_token(MAIN);
    jj_consume_token(ABRE_PAR);
    jj_consume_token(FECHA_PAR);
    jj_consume_token(BEGIN);
    vars = VarDecls();
    coms = SeqComandos();
    jj_consume_token(END);
     {if (true) return new Main(vars,coms);}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<VarDecl> VarDecls() throws ParseException {
 ArrayList<VarDecl> decls = new ArrayList<VarDecl>(); Token nome=null; String tipo=null;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LET:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(LET);
      tipo = Tipo();
      nome = jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PONTO_VIRGULA);
      decls.add(new VarDecl(tipo,nome.image));
    }
     {if (true) return decls;}
    throw new Error("Missing return statement in function");
  }

  final public String Tipo() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FLOAT:
      t = jj_consume_token(FLOAT);
               {if (true) return "Float";}
      break;
    case BOOLEAN:
      t = jj_consume_token(BOOLEAN);
                 {if (true) return "Bool";}
      break;
    case VOID:
      t = jj_consume_token(VOID);
              {if (true) return "Void";}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<Comando> SeqComandos() throws ParseException {
 ArrayList<Comando> comandos = new ArrayList<Comando>(); Comando c=null;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case RETURN:
      case PRINT:
      case IDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      c = Com();
              comandos.add(c);
    }
     {if (true) return comandos;}
    throw new Error("Missing return statement in function");
  }

  final public Comando Com() throws ParseException {
 Token id=null; Token t=null; ast.Exp exp=null; ArrayList<Comando> bloco=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      id = jj_consume_token(IDENTIFICADOR);
                        {if (true) return ComId(id);}
      break;
    case IF:
      t = jj_consume_token(IF);
      exp = Exp();
      jj_consume_token(BEGIN);
      bloco = SeqComandos();
      jj_consume_token(END);
      jj_consume_token(PONTO_VIRGULA);
     {if (true) return new CIf(t.beginLine,exp,bloco);}
      break;
    case WHILE:
      t = jj_consume_token(WHILE);
      exp = Exp();
      jj_consume_token(BEGIN);
      bloco = SeqComandos();
      jj_consume_token(END);
      jj_consume_token(PONTO_VIRGULA);
     {if (true) return new CWhile(t.beginLine,exp,bloco);}
      break;
    case RETURN:
      t = jj_consume_token(RETURN);
      exp = Exp();
      jj_consume_token(PONTO_VIRGULA);
     {if (true) return new CReturn(t.beginLine,exp);}
      break;
    case PRINT:
      t = jj_consume_token(PRINT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ABRE_PAR:
      case TRUE:
      case FALSE:
      case IDENTIFICADOR:
      case NUM:
        exp = Exp();
        break;
      case STRING:
        t = jj_consume_token(STRING);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(PONTO_VIRGULA);
     {if (true) return new CPrint(t.beginLine,exp);}
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Comando ComId(Token idTok) throws ParseException {
 ast.Exp exp=null; ArrayList<ast.Exp> args=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ATRIBUICAO:
      jj_consume_token(ATRIBUICAO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ABRE_PAR:
      case TRUE:
      case FALSE:
      case IDENTIFICADOR:
      case NUM:
        exp = Exp();
        jj_consume_token(PONTO_VIRGULA);
         {if (true) return new CAtribuicao(idTok.beginLine,idTok.image,exp);}
        break;
      case READ:
        jj_consume_token(READ);
        jj_consume_token(ABRE_PAR);
        jj_consume_token(FECHA_PAR);
        jj_consume_token(PONTO_VIRGULA);
         {if (true) return new CReadInput(idTok.beginLine,idTok.image);}
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case ABRE_PAR:
      jj_consume_token(ABRE_PAR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ABRE_PAR:
      case TRUE:
      case FALSE:
      case IDENTIFICADOR:
      case NUM:
        args = ListaExp();
        break;
      default:
        jj_la1[7] = jj_gen;
        ;
      }
      jj_consume_token(FECHA_PAR);
      jj_consume_token(PONTO_VIRGULA);
        if (args == null) args = new ArrayList<ast.Exp>();
        {if (true) return new CChamadaFun(idTok.beginLine,idTok.image,args);}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ast.Exp Exp() throws ParseException {
 ast.Exp exp=null;
    exp = ExpOr();
                 {if (true) return exp;}
    throw new Error("Missing return statement in function");
  }

  final public ast.Exp ExpOr() throws ParseException {
 ast.Exp left=null; ast.Exp right=null; Token op=null;
    left = ExpAnd();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      op = jj_consume_token(OR);
      right = ExpAnd();
                             left = new EOpExp(op.image,left,right);
    }
     {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public ast.Exp ExpAnd() throws ParseException {
 ast.Exp left=null; ast.Exp right=null; Token op=null;
    left = ExpRel();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      op = jj_consume_token(AND);
      right = ExpRel();
                              left = new EOpExp(op.image,left,right);
    }
     {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public ast.Exp ExpRel() throws ParseException {
 ast.Exp left=null; ast.Exp right=null; Token op=null;
    left = ExpAdd();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IGUAL:
      case MENOR_IGUAL:
      case MAIOR_IGUAL:
      case MENOR:
      case MAIOR:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IGUAL:
        op = jj_consume_token(IGUAL);
        break;
      case MENOR:
        op = jj_consume_token(MENOR);
        break;
      case MAIOR:
        op = jj_consume_token(MAIOR);
        break;
      case MENOR_IGUAL:
        op = jj_consume_token(MENOR_IGUAL);
        break;
      case MAIOR_IGUAL:
        op = jj_consume_token(MAIOR_IGUAL);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = ExpAdd();
                     left = new EOpExp(op.image,left,right);
    }
     {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public ast.Exp ExpAdd() throws ParseException {
 ast.Exp left=null; ast.Exp right=null; Token op=null;
    left = ExpMul();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIS:
      case MENOS:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIS:
        op = jj_consume_token(MAIS);
        break;
      case MENOS:
        op = jj_consume_token(MENOS);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = ExpMul();
                                              left = new EOpExp(op.image,left,right);
    }
     {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public ast.Exp ExpMul() throws ParseException {
 ast.Exp left=null; ast.Exp right=null; Token op=null;
    left = Fator();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
      case DIV:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
        op = jj_consume_token(MULT);
        break;
      case DIV:
        op = jj_consume_token(DIV);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = Fator();
                                           left = new EOpExp(op.image,left,right);
    }
     {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public ast.Exp Fator() throws ParseException {
 Token id=null; Token numTok=null; ast.Exp inner=null; ArrayList<ast.Exp> args=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      id = jj_consume_token(IDENTIFICADOR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ABRE_PAR:
        jj_consume_token(ABRE_PAR);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ABRE_PAR:
        case TRUE:
        case FALSE:
        case IDENTIFICADOR:
        case NUM:
          args = ListaExp();
          break;
        default:
          jj_la1[17] = jj_gen;
          ;
        }
        jj_consume_token(FECHA_PAR);
            if (args == null) args = new ArrayList<ast.Exp>();
            {if (true) return new EChamadaFun(id.image,args);}
        break;
      default:
        jj_la1[18] = jj_gen;
         {if (true) return new EVar(id.image);}
      }
      break;
    case NUM:
      numTok = jj_consume_token(NUM);
                  {if (true) return new EFloat(Float.parseFloat(numTok.image));}
      break;
    case TRUE:
      jj_consume_token(TRUE);
            {if (true) return new ETrue();}
      break;
    case FALSE:
      jj_consume_token(FALSE);
             {if (true) return new EFalse();}
      break;
    case ABRE_PAR:
      jj_consume_token(ABRE_PAR);
      inner = Exp();
      jj_consume_token(FECHA_PAR);
                                        {if (true) return inner;}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<ast.Exp> ListaExp() throws ParseException {
 ArrayList<ast.Exp> args = new ArrayList<ast.Exp>(); ast.Exp e=null;
    e = Exp();
             args.add(e);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_9;
      }
      jj_consume_token(VIRGULA);
      e = Exp();
                                               args.add(e);
    }
     {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  final public Fun Func() throws ParseException {
 String tipo=null; Token nome=null; ArrayList<ParamFormalFun> params=null; ArrayList<VarDecl> vars=null; ArrayList<Comando> body=null;
    jj_consume_token(DEF);
    tipo = Tipo();
    nome = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ABRE_PAR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FLOAT:
    case BOOLEAN:
    case VOID:
      params = ListaArg();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(FECHA_PAR);
    jj_consume_token(BEGIN);
    vars = VarDecls();
    body = SeqComandos();
    jj_consume_token(END);
        if (params == null) params = new ArrayList<ParamFormalFun>();
        {if (true) return new Fun(nome.image,params,tipo,vars,body);}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<ParamFormalFun> ListaArg() throws ParseException {
 ArrayList<ParamFormalFun> params = new ArrayList<ParamFormalFun>(); String tipo=null; Token nome=null;
    tipo = Tipo();
    nome = jj_consume_token(IDENTIFICADOR);
                                      params.add(new ParamFormalFun(tipo,nome.image));
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_10;
      }
      jj_consume_token(VIRGULA);
      tipo = Tipo();
      nome = jj_consume_token(IDENTIFICADOR);
                                                 params.add(new ParamFormalFun(tipo,nome.image));
    }
     {if (true) return params;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public LovelaceTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[23];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x10000,0x200,0xe00000,0xd400,0x3080000,0xd400,0x3082000,0x3080000,0x80000,0x8000000,0x4000000,0xf0000000,0xf0000000,0x0,0x0,0x0,0x0,0x3080000,0x80000,0x3080000,0x20000,0xe00000,0x20000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x80,0x1c0,0x80,0x180,0x180,0x20,0x0,0x0,0x1,0x1,0x6,0x6,0x18,0x18,0x180,0x0,0x180,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public Lovelace(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Lovelace(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new LovelaceTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Lovelace(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new LovelaceTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Lovelace(LovelaceTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(LovelaceTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[41];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 23; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 41; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
