/* Generated By:JavaCC: Do not edit this line. LovelaceConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LovelaceConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int LET = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int READ = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int DEF = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int SEMI = 17;
  /** RegularExpression Id. */
  int LPAREN = 18;
  /** RegularExpression Id. */
  int RPAREN = 19;
  /** RegularExpression Id. */
  int FLOAT_TYPE = 20;
  /** RegularExpression Id. */
  int BOOL_TYPE = 21;
  /** RegularExpression Id. */
  int VOID_TYPE = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int OR = 26;
  /** RegularExpression Id. */
  int EQEQ = 27;
  /** RegularExpression Id. */
  int LT = 28;
  /** RegularExpression Id. */
  int GT = 29;
  /** RegularExpression Id. */
  int PLUS = 30;
  /** RegularExpression Id. */
  int MINUS = 31;
  /** RegularExpression Id. */
  int MULT = 32;
  /** RegularExpression Id. */
  int DIV = 33;
  /** RegularExpression Id. */
  int ATTR = 34;
  /** RegularExpression Id. */
  int ID = 35;
  /** RegularExpression Id. */
  int NUM_LITERAL = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"main\"",
    "\"begin\"",
    "\"end\"",
    "\"let\"",
    "\"if\"",
    "\"while\"",
    "\"read\"",
    "\"return\"",
    "\"print\"",
    "\"def\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"Float\"",
    "\"Bool\"",
    "\"Void\"",
    "\"true\"",
    "\"false\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":=\"",
    "<ID>",
    "<NUM_LITERAL>",
  };

}
