/* Generated By:JavaCC: Do not edit this line. LovelaceConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LovelaceConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int LET = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int READ = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int PRINT = 15;
  /** RegularExpression Id. */
  int DEF = 16;
  /** RegularExpression Id. */
  int VIRGULA = 17;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 18;
  /** RegularExpression Id. */
  int ABRE_PAR = 19;
  /** RegularExpression Id. */
  int FECHA_PAR = 20;
  /** RegularExpression Id. */
  int FLOAT = 21;
  /** RegularExpression Id. */
  int BOOLEAN = 22;
  /** RegularExpression Id. */
  int VOID = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 29;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 30;
  /** RegularExpression Id. */
  int MENOR = 31;
  /** RegularExpression Id. */
  int MAIOR = 32;
  /** RegularExpression Id. */
  int MAIS = 33;
  /** RegularExpression Id. */
  int MENOS = 34;
  /** RegularExpression Id. */
  int MULT = 35;
  /** RegularExpression Id. */
  int DIV = 36;
  /** RegularExpression Id. */
  int ATRIBUICAO = 37;
  /** RegularExpression Id. */
  int STRING = 38;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 39;
  /** RegularExpression Id. */
  int NUM = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"main\"",
    "\"begin\"",
    "\"end\"",
    "\"let\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"read\"",
    "\"return\"",
    "\"print\"",
    "\"def\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"Float\"",
    "\"Bool\"",
    "\"Void\"",
    "\"true\"",
    "\"false\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":=\"",
    "<STRING>",
    "<IDENTIFICADOR>",
    "<NUM>",
  };

}
