/* Lovelace.java */
/* Generated By:JavaCC: Do not edit this line. Lovelace.java */
import java.io.*;

public class Lovelace implements LovelaceConstants {
    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Uso: java Lovelace <arquivo.lov>");
            return;
        }

        try {
            Lovelace parser = new Lovelace(new FileInputStream(args[0]));
            parser.Analise();
            System.out.println("\nAn\u00e1lise l\u00e9xica conclu\u00edda com sucesso!");
            parser.Lovelace();
            System.out.println("\nAn\u00e1lise sint\u00e1tica conclu\u00edda com sucesso!");
        } catch (FileNotFoundException e) {
            System.err.println("Erro: Arquivo n\u00e3o encontrado - " + args[0]);
        } catch (Exception e) {
            System.err.println("Erro durante an\u00e1lise: " + e.getMessage());
            e.printStackTrace();
        }
    }

/* ANÁLISE LÉXICA */
  final public void Analise() throws ParseException {Token t;
try {
            while (true) {
                t = getNextToken();

                if (t.kind == EOF) break;

                switch (t.kind) {
                    // Palavras reservadas
                     case MAIN: System.out.println("Palavra reservada: main"); break;
                    case BEGIN: System.out.println("Palavra reservada: begin"); break;
                    case END: System.out.println("Palavra reservada: end"); break;
                    case LET: System.out.println("Palavra reservada: let"); break;
                    case IF: System.out.println("Palavra reservada: if"); break;
                    case WHILE: System.out.println("Palavra reservada: while"); break;
                    case READ: System.out.println("Palavra reservada: read"); break;
                    case RETURN: System.out.println("Palavra reservada: return"); break;
                    case PRINT: System.out.println("Palavra reservada: print"); break;
                    case DEF: System.out.println("Palavra reservada: def"); break;

                    // Tipos
                    case FLOAT: System.out.println("Tipo: Float"); break;
                    case BOOLEAN: System.out.println("Tipo: Bool"); break;
                    case VOID: System.out.println("Tipo: Void"); break;

                    // Valores booleanos
                    case TRUE: System.out.println("Valor booleano: true"); break;
                    case FALSE: System.out.println("Valor booleano: false"); break;

                    // Operadores
                    case MAIS: System.out.println("Operador aritm\u00e9tico: +"); break;
                    case MENOS: System.out.println("Operador aritm\u00e9tico: -"); break;
                    case MULT: System.out.println("Operador aritm\u00e9tico: *"); break;
                    case DIV: System.out.println("Operador aritm\u00e9tico: /"); break;
                    case AND: System.out.println("Operador l\u00f3gico: &&"); break;
                    case OR: System.out.println("Operador l\u00f3gico: ||"); break;
                    case IGUAL: System.out.println("Operador relacional: =="); break;
                    case MENOR: System.out.println("Operador relacional: <"); break;
                    case MAIOR: System.out.println("Operador relacional: >"); break;
                    case ATRIBUICAO: System.out.println("Operador de atribui\u00e7\u00e3o: :="); break;

                    // Delimitadores e pontuação
                    case ABRE_PAR: System.out.println("Abre par\u00eanteses: ("); break;
                    case FECHA_PAR: System.out.println("Fecha par\u00eanteses: )"); break;
                    case VIRGULA: System.out.println("V\u00edrgula: ,"); break;
                    case PONTO_VIRGULA: System.out.println("Ponto e v\u00edrgula: ;"); break;

                    // Identificador
                    case IDENTIFICADOR: System.out.println("Identificador: " + t.image); break;

                    // Número literal
                    case NUM: System.out.println("N\u00famero: " + t.image); break;

                    default: System.out.println("Token desconhecido: " + t.image); break;
                }
            }
        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
        }
}

/* ANÁLISE SINTÁTICA */

// Função inicial Lovelace
  final public void Lovelace() throws ParseException {
    LovMain();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEF:{
      Func();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    jj_consume_token(0);
}

// Main
  final public void LovMain() throws ParseException {
    jj_consume_token(MAIN);
    jj_consume_token(ABRE_PAR);
    jj_consume_token(FECHA_PAR);
    jj_consume_token(BEGIN);
    VarDecls();
    SeqComandos();
    jj_consume_token(END);
}

  final public void VarDecls() throws ParseException {
    VarDecl();
    jj_consume_token(PONTO_VIRGULA);
    VarDeclsL();
}

  final public void VarDeclsL() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LET:{
      VarDecl();
      jj_consume_token(PONTO_VIRGULA);
      VarDeclsL();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
}

  final public void VarDecl() throws ParseException {
    jj_consume_token(LET);
    Tipo();
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(PONTO_VIRGULA);
}

  final public void Tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FLOAT:{
      jj_consume_token(FLOAT);
      break;
      }
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
      break;
      }
    case VOID:{
      jj_consume_token(VOID);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void SeqComandos() throws ParseException {
    Com();
    SeqComandosL();
}

  final public void SeqComandosL() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IF:
    case WHILE:
    case RETURN:
    case PRINT:
    case IDENTIFICADOR:{
      Com();
      SeqComandosL();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
}

  final public void Com() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(ATRIBUICAO);
      Exp();
      jj_consume_token(PONTO_VIRGULA);
      break;
      }{
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(ABRE_PAR);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABRE_PAR:
      case TRUE:
      case FALSE:
      case IDENTIFICADOR:
      case NUM:{
        ListaExp();
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        ;
      }
      jj_consume_token(FECHA_PAR);
      jj_consume_token(PONTO_VIRGULA);
      break;
      }
    case IF:{
      jj_consume_token(IF);
      Exp();
      jj_consume_token(BEGIN);
      SeqComandos();
      jj_consume_token(END);
      jj_consume_token(PONTO_VIRGULA);
      break;
      }
    case WHILE:{
      jj_consume_token(WHILE);
      Exp();
      jj_consume_token(BEGIN);
      SeqComandos();
      jj_consume_token(END);
      jj_consume_token(PONTO_VIRGULA);
      break;
      }{
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(ATRIBUICAO);
      jj_consume_token(READ);
      jj_consume_token(ABRE_PAR);
      jj_consume_token(FECHA_PAR);
      jj_consume_token(PONTO_VIRGULA);
      break;
      }
    case RETURN:{
      jj_consume_token(RETURN);
      Exp();
      jj_consume_token(PONTO_VIRGULA);
      break;
      }
    case PRINT:{
      jj_consume_token(PRINT);
      Exp();
      jj_consume_token(PONTO_VIRGULA);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Exp() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      ExpD();
      Op();
      ExpD();
      jj_consume_token(FECHA_PAR);
      break;
      }
    case TRUE:
    case FALSE:
    case IDENTIFICADOR:
    case NUM:{
      Fator();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void ExpD() throws ParseException {
    Fator();
    ExpDD();
}

  final public void ExpDD() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MAIS:
    case MENOS:
    case MULT:
    case DIV:{
      Op();
      Exp();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
}

  final public void Fator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }{
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(ABRE_PAR);
      ListaExp();
      jj_consume_token(FECHA_PAR);
      break;
      }
    case NUM:{
      jj_consume_token(NUM);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Op() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MAIS:{
      jj_consume_token(MAIS);
      break;
      }
    case MENOS:{
      jj_consume_token(MENOS);
      break;
      }
    case MULT:{
      jj_consume_token(MULT);
      break;
      }
    case DIV:{
      jj_consume_token(DIV);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void ListaExp() throws ParseException {
    Exp();
    ListaExpL();
}

  final public void ListaExpL() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VIRGULA:{
      jj_consume_token(VIRGULA);
      Exp();
      ListaExpL();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
}

  final public void Func() throws ParseException {
    jj_consume_token(DEF);
    Tipo();
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ABRE_PAR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FLOAT:
    case BOOLEAN:
    case VOID:{
      ListaArg();
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(FECHA_PAR);
    jj_consume_token(BEGIN);
    VarDecls();
    SeqComandos();
    jj_consume_token(END);
    FuncL();
}

  final public void FuncL() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEF:{
      Func();
      FuncL();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
}

  final public void ListaArg() throws ParseException {
    Tipo();
    jj_consume_token(IDENTIFICADOR);
    ListaArgL();
}

  final public void ListaArgL() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VIRGULA:{
      jj_consume_token(VIRGULA);
      Tipo();
      jj_consume_token(IDENTIFICADOR);
      ListaArgL();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
}

  /** Generated Token Manager. */
  public LovelaceTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x8000,0x200,0x700000,0x6c00,0x1840000,0x6c00,0x1840000,0xc0000000,0x1800000,0xc0000000,0x10000,0x700000,0x8000,0x10000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x8,0x18,0x8,0x18,0x3,0x18,0x3,0x0,0x0,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public Lovelace(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Lovelace(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new LovelaceTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Lovelace(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new LovelaceTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new LovelaceTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Lovelace(LovelaceTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(LovelaceTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[37];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 14; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 37; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
