/* Generated By:JavaCC: Do not edit this line. LovelaceConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LovelaceConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINHA = 6;
  /** RegularExpression Id. */
  int COMENTARIO_BLOCO = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int BEGIN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int LET = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int THEN = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int READ = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int FUNCTION = 20;
  /** RegularExpression Id. */
  int PROCEDURE = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int BOOLEAN = 24;
  /** RegularExpression Id. */
  int STRING = 25;
  /** RegularExpression Id. */
  int TRUE = 26;
  /** RegularExpression Id. */
  int FALSE = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int DIFERENTE = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 31;
  /** RegularExpression Id. */
  int MAIOR = 32;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int MAIS = 37;
  /** RegularExpression Id. */
  int MENOS = 38;
  /** RegularExpression Id. */
  int MULT = 39;
  /** RegularExpression Id. */
  int DIV = 40;
  /** RegularExpression Id. */
  int MOD = 41;
  /** RegularExpression Id. */
  int ABRE_PAR = 42;
  /** RegularExpression Id. */
  int FECHA_PAR = 43;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 44;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 45;
  /** RegularExpression Id. */
  int ABRE_COLCHETE = 46;
  /** RegularExpression Id. */
  int FECHA_COLCHETE = 47;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 48;
  /** RegularExpression Id. */
  int VIRGULA = 49;
  /** RegularExpression Id. */
  int DOIS_PONTOS = 50;
  /** RegularExpression Id. */
  int PONTO = 51;
  /** RegularExpression Id. */
  int ATRIBUICAO = 52;
  /** RegularExpression Id. */
  int NUMERO_FLOAT = 53;
  /** RegularExpression Id. */
  int NUMERO_INT = 54;
  /** RegularExpression Id. */
  int STRING_LITERAL = 55;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<COMENTARIO_LINHA>",
    "<COMENTARIO_BLOCO>",
    "\"main\"",
    "\"begin\"",
    "\"end\"",
    "\"let\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"function\"",
    "\"procedure\"",
    "\"Int\"",
    "\"Float\"",
    "\"Boolean\"",
    "\"String\"",
    "\"true\"",
    "\"false\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\".\"",
    "\":=\"",
    "<NUMERO_FLOAT>",
    "<NUMERO_INT>",
    "<STRING_LITERAL>",
    "<IDENTIFICADOR>",
  };

}
