/* Generated By:JavaCC: Do not edit this line. Lovelace.java */
import java.io.*;

public class Lovelace implements LovelaceConstants {
    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Uso: java Lovelace <arquivo.lov>");
            return;
        }

        try {
            Lovelace parser = new Lovelace(new FileInputStream(args[0]));
            parser.Analise();
            System.out.println("\nAn\u00e1lise l\u00e9xica conclu\u00edda com sucesso!");
        } catch (FileNotFoundException e) {
            System.err.println("Erro: Arquivo n\u00e3o encontrado - " + args[0]);
        } catch (Exception e) {
            System.err.println("Erro durante an\u00e1lise: " + e.getMessage());
            e.printStackTrace();
        }
    }

/* ANÁLISE LÉXICA */
  final public void Analise() throws ParseException {
    Token t;
        try {
            while (true) {
                t = getNextToken();

                if (t.kind == EOF) break;

                switch (t.kind) {
                    // Palavras reservadas
                    case MAIN: System.out.println("Palavra reservada: main"); break;
                    case BEGIN: System.out.println("Palavra reservada: begin"); break;
                    case END: System.out.println("Palavra reservada: end"); break;
                    case LET: System.out.println("Palavra reservada: let"); break;
                    case IF: System.out.println("Palavra reservada: if"); break;
                    case THEN: System.out.println("Palavra reservada: then"); break;
                    case ELSE: System.out.println("Palavra reservada: else"); break;
                    case WHILE: System.out.println("Palavra reservada: while"); break;
                    case DO: System.out.println("Palavra reservada: do"); break;
                    case PRINT: System.out.println("Palavra reservada: print"); break;
                    case READ: System.out.println("Palavra reservada: read"); break;
                    case RETURN: System.out.println("Palavra reservada: return"); break;
                    case FUNCTION: System.out.println("Palavra reservada: function"); break;
                    case PROCEDURE: System.out.println("Palavra reservada: procedure"); break;

                    // Tipos
                    case INT: System.out.println("Palavra reservada: Int"); break;
                    case FLOAT: System.out.println("Palavra reservada: Float"); break;
                    case BOOLEAN: System.out.println("Palavra reservada: Boolean"); break;
                    case STRING: System.out.println("Palavra reservada: String"); break;

                    // Valores booleanos
                    case TRUE: System.out.println("Valor booleano: true"); break;
                    case FALSE: System.out.println("Valor booleano: false"); break;

                    // Operadores relacionais
                    case IGUAL: System.out.println("Operador relacional: =="); break;
                    case DIFERENTE: System.out.println("Operador relacional: !="); break;
                    case MENOR: System.out.println("Operador relacional: <"); break;
                    case MENOR_IGUAL: System.out.println("Operador relacional: <="); break;
                    case MAIOR: System.out.println("Operador relacional: >"); break;
                    case MAIOR_IGUAL: System.out.println("Operador relacional: >="); break;

                    // Operadores lógicos
                    case AND: System.out.println("Operador l\u00f3gico: &&"); break;
                    case OR: System.out.println("Operador l\u00f3gico: ||"); break;
                    case NOT: System.out.println("Operador l\u00f3gico: !"); break;

                    // Operadores aritméticos
                    case MAIS: System.out.println("Operador aritm\u00e9tico: +"); break;
                    case MENOS: System.out.println("Operador aritm\u00e9tico: -"); break;
                    case MULT: System.out.println("Operador aritm\u00e9tico: *"); break;
                    case DIV: System.out.println("Operador aritm\u00e9tico: /"); break;
                    case MOD: System.out.println("Operador aritm\u00e9tico: %"); break;

                    // Delimitadores
                    case ABRE_PAR: System.out.println("Abre par\u00eanteses: ("); break;
                    case FECHA_PAR: System.out.println("Fecha par\u00eanteses: )"); break;
                    case ABRE_CHAVE: System.out.println("Abre chaves: {"); break;
                    case FECHA_CHAVE: System.out.println("Fecha chaves: }"); break;
                    case ABRE_COLCHETE: System.out.println("Abre colchetes: ["); break;
                    case FECHA_COLCHETE: System.out.println("Fecha colchetes: ]"); break;
                    case PONTO_VIRGULA: System.out.println("Ponto e v\u00edrgula: ;"); break;
                    case VIRGULA: System.out.println("V\u00edrgula: ,"); break;
                    case DOIS_PONTOS: System.out.println("Dois pontos: :"); break;
                    case PONTO: System.out.println("Ponto: ."); break;

                    // Atribuição
                    case ATRIBUICAO: System.out.println("Atribui\u00e7\u00e3o: :="); break;

                    // Números
                    case NUMERO_FLOAT: System.out.println("N\u00famero: " + t.image); break;
                    case NUMERO_INT: System.out.println("N\u00famero: " + t.image); break;

                    // String literal
                    case STRING_LITERAL: System.out.println("String: " + t.image); break;

                    // Identificador
                    case IDENTIFICADOR: System.out.println("Identificador: " + t.image); break;

                    default: System.out.println("Token desconhecido: " + t.image); break;
                }
            }
        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
        }
  }

  /** Generated Token Manager. */
  public LovelaceTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }

  /** Constructor with InputStream. */
  public Lovelace(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Lovelace(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new LovelaceTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Lovelace(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new LovelaceTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Lovelace(LovelaceTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(LovelaceTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[57];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 57; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
